spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/pizzahouse
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
      enabled: true

jwt:
  privateKey: keyVIImZZAayFfHB8Ej0Z+se/qzj9rWcAEGZ3DHyc9HpQZOf8RdjQOXAktUTM1x2fcxYi+aI0dW24uSpUpna+Zgtg==

uploadFile:
  rootPath: D:\pizzahouse\uploads